name: stock-bot-scheduler

on:
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:

jobs:
  ai-job:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get code
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: 3. Install Lips
        run : pip install yfinance pandas pandas-ta requests

      - name: 4. Run AI
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK}}
        run: python stock_bot.py